### ISSUE TITLE
spec: infix notation operator precedence

### ISSUE THREAD

**Issue by fexolm** [emacs-lang-dev/spec#1]
It looks like `[ a + b * c ] => (* (+ a b) c)` has non intuitive semantics. We have to decide if we would correctly process such expressions, or forbid writing it without parentheses.

**Comment by quasilyte** [comment]
There is no `operator precedence` term in this language.
I don't know a single lisp that have it.

**Comment by quasilyte** [comment]
The `[x f1 y f2 z]` is a sugared `[[x f1 y] f2 z]` which is a sugared form of `(f2 (f1 x y) z)`, just for readability. Less parenthesis and simpler control flow (reading from left to right).
In a sense, it's like a limited threading macro:
```
;; thread-last (requires lodash lib)
(->> y (+ x) (* c))
```
But `[x + y * c]` is easier to type and read.

Here is complete example, for convenience (doesn't require lodash):
```elisp
(require 'subr-x)
(let ((x 2)
      (y 3)
      (c 4))
  (thread-last y (+ x) (* c)))
```

**Comment by quasilyte** [comment]
Maybe this can help: `+` and `*` are not "operators", they are ordinary functions.
And expression inside `[]` is not mathematical expression either, it has no notion of precedence.
It's more like a pipeline from bash where you can carry evaluation result from the previous evaluation as an input for another.
